apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: boardgame
  namespace: webapps  # Optional: remove if using default namespace
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: ayyubkhancs/boardgame-canary:v1
        ports:
        - containerPort: 8080
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 1m }
      - setWeight: 100
